apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
data:
  primary.conf: |-
{{ .Values.config.primary | indent 4 }}
  replica.conf: |-
{{ .Values.config.replica | indent 4 }}
