apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  clusterIP: None
  selector:
    app: {{ include "redis.fullname" . }}-sts
